services:
  mysql:
    image: mysql:8.4
    container_name: potatos_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: potatos_app
      MYSQL_USER: potatos
      MYSQL_PASSWORD: potatos123
    ports:
      - "3306:3306"
    volumes:
      - potatos_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  potatos_mysql_data:
